### ISSUE TITLE
ViteJS Vue3 import error

### ISSUE THREAD

**Issue by Prutheus** [justcaliturner/simple-code-editor#2]
I use vitejs with vue3 and want to use the `simple-code-editor`.

However, I do a import in my `.vue` file like this: `import CodeEditor from "simple-code-editor"` but this fails with following error:

```
[plugin:vite:import-analysis] Failed to resolve import "./Dropdown" from "node_modules/simple-code-editor/CodeEditor.vue". Does the file exist?
/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/simple-code-editor/CodeEditor.vue:3:25
1  |  
2  |  import hljs from "highlight.js";
3  |  import Dropdown from "./Dropdown";
   |                          ^
4  |  import CopyCode from "./CopyCode";
5  |
    at formatError (/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42189:46)
    at TransformContext.error (/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42185:19)
    at normalizeUrl (/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67284:26)
    at async TransformContext.transform (/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:67424:57)
    at async Object.transform (/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
    at async doTransform (/Users/prutheus/WebstormProjects/xxx/xxx/xxx/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29
Click outside or fix the code to dismiss.
You can also disable this overlay by setting server.hmr.overlay to false in vite.config.js.
```

Why does this happen and how I can solve this?

**Comment by justcaliturner** [comment]
Oh, It's my mistake, I missed the suffixes of the imported files, and it's fixed,  you can update it and try again, thank you for your comment.

**Comment by justcaliturner** [comment]
@Prutheus  Oh, It's my mistake, I missed the suffixes of the imported files, and it's fixed, you can update it and try again, thank you for your comment.

**Comment by justcaliturner** [comment]
Thank you for your comment, this is my mistake, I missed the suffixes of
the imported files, I have fixed it, you can update it and try again later.
If there are still errors, please let me know. Thanks again.


Prutheus ***@***.***> 于2021年11月19日周五 下午11:26写道：
